# Generated by Django 2.2.6 on 2020-01-07 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(default=1, unique=True, verbose_name='Чат ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Пользователь')),
                ('lang_code', models.CharField(max_length=2, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['chat_id'],
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('date_msg', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата сообщения')),
                ('chatM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitr24.Chat', verbose_name='Чат ID')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Bitr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bx24_id', models.IntegerField(default=0, unique=True, verbose_name='ID пользователя Б24')),
                ('access_token', models.CharField(blank=True, max_length=150, null=True, verbose_name='Токен доступа Б24')),
                ('refresh_token', models.CharField(blank=True, max_length=150, null=True, verbose_name='Токен обновления Б24')),
                ('chatB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitr24.Chat', verbose_name='Чат ID')),
            ],
            options={
                'verbose_name': 'Пользователь Б24',
                'verbose_name_plural': 'Пользователи Б24',
                'ordering': ['bx24_id'],
            },
        ),
    ]
