# Generated by Django 2.2.11 on 2020-05-08 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bx24_id', models.IntegerField(default=0, unique=True, verbose_name='ID поль. Б24')),
                ('bx24_name', models.CharField(db_index=True, default='', max_length=100, verbose_name='Имя в Б24')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг(Slug)')),
                ('expires', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время Acc токена')),
                ('access_token', models.CharField(blank=True, max_length=150, null=True, verbose_name='Токен доступа Б24')),
                ('refresh_token', models.CharField(blank=True, max_length=150, null=True, verbose_name='Токен обновления Б24')),
                ('date_bx24', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата подкл. к Б24')),
            ],
            options={
                'verbose_name': 'Данные Б24',
                'verbose_name_plural': 'Данные Б24',
                'ordering': ['-expires'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(default=0, unique=True, verbose_name='Чат ID')),
                ('first_name', models.CharField(db_index=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(db_index=True, max_length=100, verbose_name='Фамилия')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг(Slug)')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('lang_code', models.CharField(max_length=2, verbose_name='Язык')),
                ('date_chat', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата подкл.к боту')),
                ('bitrs', models.ManyToManyField(blank=True, related_name='chats', to='bitr24.Bitr', verbose_name='Имя в Битрикс24')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты телеграм бота',
                'ordering': ['-date_chat'],
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('date_msg', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата сообщения')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bitr24.Chat', verbose_name='Chat: ID, Имя')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-date_msg'],
            },
        ),
    ]
