# Generated by Django 2.2.6 on 2020-01-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitr24', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitr',
            name='expires',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Время Acc токена'),
        ),
        migrations.AlterField(
            model_name='bitr',
            name='bx24_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='ID поль. Б24'),
        ),
        migrations.AlterField(
            model_name='bitr',
            name='bx24_name',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='Имя в Б24'),
        ),
        migrations.AlterField(
            model_name='bitr',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг(Slug)'),
        ),
    ]
