# Generated by Django 2.2.6 on 2020-03-13 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitr24', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitr',
            options={'ordering': ['-expires'], 'verbose_name': 'Данные Б24', 'verbose_name_plural': 'Данные Б24'},
        ),
        migrations.AddField(
            model_name='bitr',
            name='expires',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Время Acc токена'),
        ),
        migrations.AlterField(
            model_name='bitr',
            name='bx24_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='ID поль. Б24'),
        ),
        migrations.AlterField(
            model_name='bitr',
            name='bx24_name',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='Имя в Б24'),
        ),
        migrations.AlterField(
            model_name='bitr',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг(Slug)'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='Чат ID'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bitr24.Chat', verbose_name='Chat: ID, Имя'),
        ),
    ]
