# Generated by Django 2.2.6 on 2020-01-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitr24', '0002_auto_20200130_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitr',
            name='expires',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30, null=True, verbose_name='Время Acc токена'),
        ),
    ]
