# Generated by Django 2.2.6 on 2020-01-08 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitr24', '0002_auto_20200108_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitr',
            name='chatB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitr24.Chat', verbose_name='Чат ID, Пользователь'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='chatM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bitr24.Chat', verbose_name='Чат ID, Пользователь'),
        ),
    ]
