# Generated by Django 2.2.6 on 2020-01-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitr24', '0003_auto_20200108_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='first_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='chats',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date_msg',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата сообщения'),
        ),
    ]
