# Generated by Django 2.2.6 on 2020-02-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitr24', '0003_auto_20200130_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(default=1, unique=True, verbose_name='Чат ID')),
                ('bx24_id', models.IntegerField(default=0, unique=True, verbose_name='ID поль. Б24')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Посл.сообщение')),
                ('date_bind', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата сообщения')),
            ],
            options={
                'verbose_name': 'Привязка',
                'verbose_name_plural': 'Привязки',
                'ordering': ['-date_bind'],
            },
        ),
    ]
