# Generated by Django 2.2.6 on 2020-02-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitr24', '0004_bind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bind',
            name='chat_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='Чат ID'),
        ),
        migrations.AlterField(
            model_name='bind',
            name='date_bind',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата привязки'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='Чат ID'),
        ),
    ]
