# Generated by Django 2.2.6 on 2020-01-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitr24', '0004_auto_20200110_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitr',
            options={'ordering': ['bx24_id'], 'verbose_name': 'Данные Б24', 'verbose_name_plural': 'Данные Б24'},
        ),
        migrations.AlterField(
            model_name='chats',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
