# Generated by Django 2.2.6 on 2020-01-10 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitr24', '0005_auto_20200110_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chats',
            options={'ordering': ['chat_id'], 'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты телеграм бота'},
        ),
    ]
