# Generated by Django 2.2.6 on 2020-02-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitr24', '0005_auto_20200202_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bind',
            name='bx24_id',
            field=models.IntegerField(db_index=True, default=0, verbose_name='ID поль. Б24'),
        ),
    ]
