# Generated by Django 2.2.6 on 2020-01-11 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitr24', '0007_auto_20200111_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='chatM',
        ),
    ]
