# Generated by Django 2.2.6 on 2020-01-13 03:24

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('bitr24', '0009_bitr_bx24_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chats',
            new_name='Chat',
        ),
    ]
