# Generated by Django 2.2.6 on 2020-01-15 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bitr24', '0010_auto_20200113_0324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitr',
            options={'ordering': ['-date_bx24'], 'verbose_name': 'Данные Б24', 'verbose_name_plural': 'Данные Б24'},
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-date_chat'], 'verbose_name': 'Чат', 'verbose_name_plural': 'Чаты телеграм бота'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-date_msg'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='bitr',
            name='date_bx24',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата подкл. к Б24'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='date_chat',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата подкл.к боту'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bitr',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Слаг(Slug)'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг(Slug)'),
        ),
    ]
