# Generated by Django 2.2.11 on 2020-04-07 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0004_auto_20200102_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ордена')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='Код ордена')),
            ],
            options={
                'verbose_name': 'Орден',
                'verbose_name_plural': 'Ордена',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Планета')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Слаг(Slug)')),
            ],
            options={
                'verbose_name': 'Планета',
                'verbose_name_plural': 'Планеты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя рекрута')),
                ('age', models.IntegerField(default=1, verbose_name='Возраст')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Емаил')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Слаг(Slug)')),
                ('answers', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответы')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruits', to='si.Planet', verbose_name='Планета')),
            ],
            options={
                'verbose_name': 'Рекрут',
                'verbose_name_plural': 'Рекруты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Вопрос')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Слаг(Slug)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='si.Order', verbose_name='Код ордена')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='recruits',
            name='planet',
        ),
        migrations.DeleteModel(
            name='Tests',
        ),
        migrations.AddField(
            model_name='sith',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Слаг(Slug)'),
        ),
        migrations.AlterField(
            model_name='sith',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siths', to='si.Planet', verbose_name='Планета'),
        ),
        migrations.DeleteModel(
            name='Planets',
        ),
        migrations.DeleteModel(
            name='Recruits',
        ),
        migrations.AddField(
            model_name='recruit',
            name='sith',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruits', to='si.Sith', verbose_name='Рука Тени'),
        ),
        migrations.AddField(
            model_name='sith',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='siths', to='si.Order', verbose_name='Код ордена'),
        ),
    ]
