# Generated by Django 2.2.11 on 2020-04-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0005_auto_20200408_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('tests', models.ManyToManyField(blank=True, related_name='tests', to='si.Test', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['answer'],
            },
        ),
    ]
