# Generated by Django 2.2.11 on 2020-04-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0006_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='answers', to='si.Test', verbose_name='Вопрос'),
        ),
    ]
