# Generated by Django 2.2.11 on 2020-05-08 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0007_auto_20200423_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
    ]
