# Generated by Django 2.2.11 on 2020-05-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0009_order_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='tests',
        ),
        migrations.AddField(
            model_name='test',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='tests', to='si.Answer', verbose_name='Ответ'),
        ),
    ]
