# Generated by Django 2.2.11 on 2020-07-07 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0011_recruitanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitanswer',
            options={'ordering': ['recruit'], 'verbose_name': 'Ответы Рекрута', 'verbose_name_plural': 'Ответы Рекрутов'},
        ),
    ]
