# Generated by Django 2.2.11 on 2020-07-08 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0013_test_right_answ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='right_answ',
        ),
        migrations.AddField(
            model_name='test',
            name='right_answ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='right_answ', to='si.Answer', verbose_name='Правильный ответ'),
        ),
    ]
