# Generated by Django 2.2.11 on 2020-07-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0014_auto_20200708_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-pk'], 'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
    ]
