# Generated by Django 2.2.11 on 2020-07-15 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0016_auto_20200715_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitanswer',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruitanswers', to='si.Answer', verbose_name='Ответ'),
        ),
    ]
