# Generated by Django 2.2.11 on 2020-07-19 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('si', '0017_auto_20200715_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitanswer',
            name='recruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitanswers', to='si.Recruit', verbose_name='Рекрут'),
        ),
    ]
