# Generated by Django 2.2.6 on 2019-12-26 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('date_msg', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['date_msg'],
            },
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(default=1, verbose_name='Чат ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('username', models.CharField(max_length=50, verbose_name='Пользователь')),
                ('lang_code', models.CharField(max_length=2, verbose_name='Пользователь')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bitrix24.Messages', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'ordering': ['chat_id'],
            },
        ),
    ]
