# Generated by Django 2.2.6 on 2019-12-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix24', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['pk'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='chats',
            name='lang_code',
            field=models.CharField(max_length=2, verbose_name='Язык'),
        ),
    ]
