# Generated by Django 2.2.6 on 2019-12-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix24', '0002_auto_20191226_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats',
            name='chat_id',
            field=models.IntegerField(default=1, unique=True, verbose_name='Чат ID'),
        ),
    ]
